# Offense count: 32
Documentation:
  Enabled: false

# Offense count: 359
#LineLength:
#  Max: 202

# Offense count: 4
# Cop supports --auto-correct.
NumericLiterals:
  MinDigits: 7

# Offense count: 3
# Configuration parameters: CountKeywordArgs.
ParameterLists:
  Max: 7

# Offense count: 2
# Configuration parameters: SupportedStyles.
RaiseArgs:
  EnforcedStyle: compact

